### ISSUE TITLE
[Feature Request]: Make Jumping and sliding animation

### ISSUE THREAD

**Issue by Tusharjain123** [bsoc-bitbyte/2D-Platformer#5]
### Is your feature request related to a problem? Please describe.

For making a game more attractive, animations like jumping and sliding are required.

### Describe the solution you'd like

Proper animation of jumping and sliding such that it makes the gameplay more easier and attractive

**Comment by Captain-T2004** [comment]
@Tusharjain123 I would like to work on this issue. Kindly assign this to me.

**Comment by Tusharjain123** [comment]
Yeah, sure
